# Generated by Django 4.2.11 on 2024-04-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("title", models.CharField(max_length=25, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events", verbose_name="Imagem"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("title", models.CharField(max_length=25, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news", verbose_name="Imagem"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=25, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("address", models.CharField(max_length=50, verbose_name="Endereço")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="places", verbose_name="Imagem"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locais",
            },
        ),
        migrations.CreateModel(
            name="RestaurantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=25, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Restaurante",
                "verbose_name_plural": "Categorias de Restaurantes",
            },
        ),
        migrations.CreateModel(
            name="TouristSpotCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=25, verbose_name="Nome")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Ponto Turístico",
                "verbose_name_plural": "Categorias de Pontos Turísticos",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="belemtrip.place",
                    ),
                ),
                (
                    "star",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Estrelas",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hoteis",
            },
            bases=("belemtrip.place",),
        ),
        migrations.CreateModel(
            name="TouristSpot",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="belemtrip.place",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Telefone")),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belemtrip.touristspotcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto Turístico",
                "verbose_name_plural": "Pontos Turísticos",
            },
            bases=("belemtrip.place",),
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="belemtrip.place",
                    ),
                ),
                (
                    "star",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Estrelas",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belemtrip.restaurantcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurante",
                "verbose_name_plural": "Restaurantes",
            },
            bases=("belemtrip.place",),
        ),
    ]
