# Generated by Django 4.2.11 on 2024-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("belemtrip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hour",
            field=models.TimeField(default=None, verbose_name="Hora"),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Local"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="news",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default=None, verbose_name="Data"),
        ),
    ]
