# Generated by Django 4.2.11 on 2024-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belemtrip', '0002_event_hour_event_location_event_website_news_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local'),
        ),
    ]
