# Generated by Django 4.2.11 on 2024-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("belemtrip", "0004_place_coordenada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
    ]
